# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Get and store current deploymentId
        run: |
          OLD_DEPLOYMENT_ID=$(npm pkg get version)
          echo "::set-output name=OLD_DEPLOYMENT_ID::$OLD_DEPLOYMENT_ID"
        id: old-deployment-id
      - name: Echo old deployment before deploy
        run: |
          echo "${{ steps.old-deployment-id.outputs.OLD_DEPLOYMENT_ID }}-{{github.run_attempt}}"
      - run: npm ci
      - run: npm run ng -- build components
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      
  version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm pkg get version
        id: getversion
      - run: |
          echo "${{steps.getversion.outputs.stdout}}-${{github.run_attempt}}"
      - run: npm pkg set version="${{steps.getversion.outputs.stdout}}-${{github.run_attempt}}"
        working-directory: ./dist/components
      - run: cat package.json
      - run: cat package.json
        working-directory: ./dist/components
      - run: |
          git status
          
  publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            token: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: ls dist
      - run: npm publish
        working-directory: ./dist/components
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      
