# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Get current package version
        run: |
          PACKAGE_VERSION=$(npm pkg get version)
          BUILD_NUMBER=${{github.run_number}}
          echo "::set-output name=PACKAGE_VERSION::$(PACKAGE_VERSION)-$(BUILD_NUMBER)"
        id: set-package-version
      - run: npm pkg set version "${{ steps.echo-package-version.outputs.PACKAGE_VERSION }}-${{github.run_attempt}}"
      - run: npm pkg set version "${{ steps.echo-package-version.outputs.PACKAGE_VERSION }}-${{github.run_attempt}}"
        working-directory: ./projects/components
      - run: npm ci
      - run: npm run ng -- build components
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      
  version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm pkg get version
      - run: cat package.json
      - run: cat package.json
        working-directory: ./dist/components
      - run: |
          git status
          
  publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            token: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: ls dist
      - run: npm publish
        working-directory: ./dist/components
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      
