# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run ng -- build components
      - run: npm run build
      - run: cp -r ./src/styles/design ./dist/components/design
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      
  version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - run: npm version prerelease
      - run: npm version prerelease
        working-directory: ./projects/components
      - run: cat package.json
      - run: cat package.json
        working-directory: ./projects/components
      - run: |
          git add --all
          git commit -m 'build'
          git push
          
  publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            token: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: ls dist
      - run: npm publish
        working-directory: ./dist/components
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      
