name: publish-github-pages
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci
      - run: npm run ng -- build design
      - run: npm run ng -- build components
      - run: npm run build -- --base-href "https://muziehdesign.github.io/designsystem/"
      - run: cp LICENSE ./dist/kitchensink-ui
      - run: cp ./dist/kitchensink-ui/index.html ./dist/kitchensink-ui/404.html
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./dist/kitchensink-ui
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          
